import SideBar from "@/components/side-bar";
import Topbar from "@/components/top-bar";
import { ModalProvider } from "@/providers/modal-provider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "WorkspaceSync",
  description: "Generated by create next app",
  icons: [
    {
      url: "/logo.svg",
      href: "/logo.svg",
    },
  ],
};

const MainLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main className="h-full w-full flex">
      <ModalProvider />
      <SideBar />
      <div className="w-full h-full">
        <Topbar />
        {children}
      </div>
    </main>
  );
};

export default MainLayout;
