import { getCurrentUser } from "@/actions/queries/getCurrentUser";
import { getProjects } from "@/actions/queries/getProjects";
import SideBar from "@/components/side-bar";
import Topbar from "@/components/top-bar";
import { ModalProvider } from "@/providers/modal-provider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "WorkspaceSync",
  description: "Generated by create next app",
  icons: [
    {
      url: "/logo.svg",
      href: "/logo.svg",
    },
  ],
};

const MainLayout = async ({ children }: { children: React.ReactNode }) => {
  const currentUser = await getCurrentUser();
  const projects = await getProjects();

  return (
    <main className="h-full w-full flex c">
      <ModalProvider />
      <SideBar role={currentUser?.role} projects={projects} />
      <div className="w-full h-full">
        <Topbar />
        {children}
      </div>
    </main>
  );
};

export default MainLayout;
